ARG RUST_VERSION=1.90-slim

FROM rust:${RUST_VERSION} AS dev

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends libpq-dev pkg-config protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add clippy rustfmt

RUN mkdir -p /app/data

EXPOSE 4000
