ARG RUST_VERSION=1.90-slim

FROM rust:${RUST_VERSION} AS dev

WORKDIR /app

COPY Cargo.toml . 

COPY src/ ./src

RUN apt-get update -y && apt-get install -y libsqlite3-dev sqlite3 && rm -rf /var/lib/apt/lists/*

RUN rustup component add clippy rustfmt

RUN mkdir -p /app/data


EXPOSE 4000
