ARG NODE_VERSION=24.9.0-alpine

FROM node:${NODE_VERSION} AS dev

ENV NODE_ENV=development

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host"], 