services:
  frontend:
    build:
      dockerfile: setup/docker/images/frontend/Dockerfile.dev
      args:
        BUN_VERSION: ${BUN_VERSION}
    image: novasound/frontend-dev:${TAG:-latest}
    working_dir: /app
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://127.0.0.1:4000}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: ["sh", "-c", "bun install --frozen-lockfile && bun run dev"]

  backend:
    build:
      dockerfile: setup/docker/images/backend/Dockerfile.dev
    image: novasound/backend-dev:${TAG:-latest}
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      APP_ENV: ${APP_ENV:-dev}
      RUST_LOG: ${RUST_LOG:-info}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:${POSTGRES_PORT}/${POSTGRES_DB}"
    ports:
      - "4000:4000"
    command: ["sleep", "infinity"]

  postgres_db:
    build:
      dockerfile: setup/docker/images/postgres/Dockerfile.dev
    image: novasound/postgres-dev:${TAG:-latest}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  backend_data:
  frontend_node_modules:
  postgres_data:
