services:
  rust:
    build:
      context: ../backend/rust
      dockerfile: ../.Docker/Dockerfile.dev
    volumes:
      - ../backend/rust:/app
    ports:
      - "3000:3000"


    command: ["cargo", "run"]

  vuejs:
    build:
      context: ../frontend/vuejs
      dockerfile: ../.Docker/Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ../frontend/vuejs/src
          target: /app/src
          action: sync
        - path: ../frontend/vuejs/package.json
          target: /app/package.json
          action: restart
        - path: ../frontend/vuejs/vite.config.js
          target: /app/vite.config.js
          action: restart      
    command: ["npm", "run", "dev"]


