services:
  # backend:
  #   container_name: Rust
  #   build:
  #     context: ../backend/.Docker
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ../backend/:/app
  #   working_dir: /app
  #   command: sleep infinity

  frontend:
    build:
      context: ../frontend/novasound-front
      dockerfile: ../.Docker/Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: restart
        - path: ./vite.config.js
          target: /app/vite.config.js
          action: restart

    command: ["npm", "run", "dev"]
