services:
  backend:
    container_name: Rust
    build:
      context: ../backend/.Docker
      dockerfile: ../.Docker/Dockerfile.dev
    develop:
      watch:
        - path: ../backend/src
          target: /app/src
          action: sync
    command: ["cargo", "run"]


  frontend:
    build:
      context: ../frontend/novasound-front
      dockerfile: ../.Docker/Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ../frontend/novasound-front/src
          target: /app/src
          action: sync
        - path: ../frontend/novasound-front/package.json
          target: /app/package.json
          action: restart
        - path: ../frontend/novasound-front/vite.config.js
          target: /app/vite.config.js
          action: restart      
    command: ["npm", "run", "dev"]