services:
  backend:
    build:
      context: ../backend
      dockerfile: .Docker/Dockerfile.dev
    volumes:
      - /rust:/app/rust
    command: sleep infinity

  frontend:
    build:
      context: ../frontend/novasound-front
      dockerfile: ../.Docker/Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: /src
          target: /app/src
          action: sync
        - path: package.json
          target: /app/package.json
          action: restart
        - path: vite.config.js
          target: /app/vite.config.js
          action: restart      
    command: ["npm", "run", "dev"]

