ARG NODE_VERSION=24.9.0-alpine

FROM node:${NODE_VERSION} AS dev

ENV NODE_ENV=development

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY frontend/. .

RUN chown -R node:node /app

USER node

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host"], 