name: CI Makefile2Doc

on:
  push:
    branches: [main, develop]
    paths: [Makefile]
  pull_request:
    branches: [main, develop]
    paths: [Makefile]

permissions:
  contents: write

jobs:
  update-doc:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6

      - name: Load tool versions
        run: cat .ci/ci-versions | grep -v '^#' | grep -v '^\s*$' >> $GITHUB_ENV

      - name: Install makefile2doc
        env:
          VERSION: ${{ env.MAKEFILE2DOC_VERSION }}
        run: |
          curl -L -o makefile2doc https://github.com/Merlin-Clos/makefile2doc/releases/download/${VERSION}/makefile2doc-linux-amd64
          chmod +x makefile2doc

      - name: Generate Documentation
        run: ./makefile2doc -o docs/MAKEFILE.md

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: auto-update MAKEFILE.md [skip ci]"
          file_pattern: docs/MAKEFILE.md
